// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSv8OJeA9IwAkVFTBVC3WQmMTRMroOJeg',
    appId: '1:495170651576:web:f40054425640cbc3b47b4d',
    messagingSenderId: '495170651576',
    projectId: 'foodapp-dee84',
    authDomain: 'foodapp-dee84.firebaseapp.com',
    storageBucket: 'foodapp-dee84.appspot.com',
    measurementId: 'G-4JX4RNLHXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcw7L0BA351jca_XQFxZ96tWx898za0SY',
    appId: '1:495170651576:android:9e2ad9656f7af165b47b4d',
    messagingSenderId: '495170651576',
    projectId: 'foodapp-dee84',
    storageBucket: 'foodapp-dee84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHBcHFGodN77ifWvuNvMr3gfcZXaN_Pmk',
    appId: '1:495170651576:ios:9dbcb6ea8868ead1b47b4d',
    messagingSenderId: '495170651576',
    projectId: 'foodapp-dee84',
    storageBucket: 'foodapp-dee84.appspot.com',
    iosBundleId: 'com.example.foodOrdering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHBcHFGodN77ifWvuNvMr3gfcZXaN_Pmk',
    appId: '1:495170651576:ios:9dbcb6ea8868ead1b47b4d',
    messagingSenderId: '495170651576',
    projectId: 'foodapp-dee84',
    storageBucket: 'foodapp-dee84.appspot.com',
    iosBundleId: 'com.example.foodOrdering',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSv8OJeA9IwAkVFTBVC3WQmMTRMroOJeg',
    appId: '1:495170651576:web:be03466fb8a5aa98b47b4d',
    messagingSenderId: '495170651576',
    projectId: 'foodapp-dee84',
    authDomain: 'foodapp-dee84.firebaseapp.com',
    storageBucket: 'foodapp-dee84.appspot.com',
    measurementId: 'G-9DT8MQD1N5',
  );
}
